set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64 CACHE STRING "" FORCE)

set(CMAKE_FIND_LIBRARY_PREFIXES "lib")
set(CMAKE_FIND_LIBRARY_SUFFICES ".a" ".so")

set(CMAKE_CXX_STANDARD 11)

set(COMPILER_TRIPLET aarch64-linux-gnu)

set(CMAKE_C_COMPILER ${COMPILER_TRIPLET}-gcc)
set(CMAKE_CXX_COMPILER ${COMPILER_TRIPLET}-g++)
