set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64 CACHE STRING "x86_64" FORCE)
set(CMAKE_CROSSCOMPILING false)

set(CMAKE_FIND_LIBRARY_PREFIXES "lib")
set(CMAKE_FIND_LIBRARY_SUFFICES ".a" ".so")

set(CMAKE_CXX_STANDARD 11)

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
